### ISSUE TITLE
计划任务执行出错

### ISSUE THREAD

**Issue by ABKQPO** [nek0us/nonebot_plugin_steam_game_status#12]
09-12 20:50:23 [ERROR] apscheduler | Job "now_steam (trigger: interval[0:01:00], next run at: 2023-09-12 20:51:23 CST)" raised an exception
Traceback (most recent call last):
  File "D:\NoneBot\ABK\bot.py", line 21, in <module>
    nonebot.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 199, in run
    uvicorn.run(
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "D:\NoneBot\ABK\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "D:\NoneBot\ABK\.venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "D:\NoneBot\ABK\.venv\lib\site-packages\nonebot_plugin_steam_game_status\__init__.py", line 130, in now_steam
    group_list = json.loads(dirpath.read_text("utf8"))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nek0us** [comment]
查看一下 bot目录/data/steam_group/group_list.json 里是否是完整的json格式，可以尝试备份该文件然后删掉它再重启bot试试

**Comment by ABKQPO** [comment]
全部都是NUL

**Comment by nek0us** [comment]
可以截图一下文件内容吗，群号记得码住

**Comment by nek0us** [comment]
试一下最新版
