### ISSUE TITLE
最新nonebot2.2.0版本加载插件会使配置文件发生错误

### ISSUE THREAD

**Issue by Hana-Akira** [nek0us/nonebot_plugin_steam_game_status#17]
group_list.json文件内这个值在2.2.0版本会变成-1导致无法加载。
![image](https://github.com/nek0us/nonebot_plugin_steam_game_status/assets/40086110/bbc164d5-4c59-4afb-a249-c7bf4c1702d3)

**Comment by nek0us** [comment]
这是之前版本添加的bot掉线后，模糊时间数据，因为它可能不是真实的

**Comment by Hana-Akira** [comment]
> 02-26 14:48:14 [ERROR] apscheduler | Job "now_steam (trigger: interval[0:01:00], next run at: 2024-02-26 14:49:14 CST)" raised an exception
Traceback (most recent call last):
  File "C:\Users\Hana-NAS\Desktop\Splatoon\bot.py", line 25, in <module>
    nonebot.run()
  File "C:\Users\Hana-NAS\Desktop\Splatoon\.venv\lib\site-packages\nonebot\__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Hana-NAS\Desktop\Splatoon\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 185, in run
    uvicorn.run(
  File "C:\Users\Hana-NAS\Desktop\Splatoon\.venv\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "C:\Users\Hana-NAS\Desktop\Splatoon\.venv\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "D:\Python3.10\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Python3.10\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "D:\Python3.10\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Python3.10\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "D:\Python3.10\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "D:\Python3.10\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "C:\Users\Hana-NAS\Desktop\Splatoon\.venv\lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\Users\Hana-NAS\Desktop\Splatoon\.venv\lib\site-packages\nonebot_plugin_steam_game_status\__init__.py", line 158, in now_steam
    group_list = json.loads(dirpath.read_text("utf8"))
  File "D:\Python3.10\lib\pathlib.py", line 1134, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "D:\Python3.10\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'data\\steam_group\\group_list.json'

nonebot2.2.0版本加载插件遇到的错误，并且配置文件数值会变-1，在2.1.3下没遇到过这个问题。数值是不会变-1的

**Comment by Hana-Akira** [comment]
重新折腾了下替换了几次旧的steamlist又好了Otz
